# Generated by Django 3.2 on 2023-02-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_yamdbuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamdbuser',
            name='password',
        ),
    ]
