# Generated by Django 3.2 on 2023-02-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_yamdbuser_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='yamdbuser',
            unique_together={('username', 'email')},
        ),
    ]
