# Generated by Django 3.2 on 2023-02-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_yamdbuser_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='yamdbuser',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='yamdbuser',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_username_email'),
        ),
    ]
