# Generated by Django 3.2 on 2023-02-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230221_1302'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='yamdbuser',
            name='unique_username_email',
        ),
    ]
